# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  CentosNodes = 1

  (1..CentosNodes).each do |i|
    config.vm.define "centosvm0#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.hostname = "centosvm0#{i}.example.com"
      node.vm.network "private_network", ip: "172.16.16.10#{i}"
      node.vm.provider "virtualbox" do |v|
        v.name = "centosvm0#{i}"
        v.memory = 1024
        v.cpus = 1
      end
      node.vm.provision "shell", path: "bootstrap_centos.sh"
    end
  end

  UbuntuNodes = 1

  (1..UbuntuNodes).each do |i|
    config.vm.define "ubuntuvm0#{i}" do |node|
      node.vm.box = "ubuntu/focal64"
      node.vm.hostname = "ubuntuvm0#{i}.example.com"
      node.vm.network "private_network", ip: "172.16.16.20#{i}"
      node.vm.provider "virtualbox" do |v|
        v.name = "ubuntuvm0#{i}"
        v.memory = 1024
        v.cpus = 1
      end
      node.vm.provision "shell", path: "bootstrap_ubuntu.sh"
    end
  end

end
