#!/bin/bash

# System admin user with sudo privileges
readonly SYSTEM_ADMIN=perforce

# Perforce admin user with no sudo privileges
readonly P4ADMIN_USER=p4adm

# Perforce binaries to download from Perforce ftp site
readonly P4BINARIES="p4"

# Install desired packages
echo "[TASK 1] Installing desired packages"
yum install -y -q vim redhat-lsb-core tree net-tools bind-utils wget git >/dev/null 2>&1

# Set up global aliases and exports
echo "[TASK 2] Creating global aliases and functions"
cat >>/etc/bashrc <<EOF
# Generated by Vagrant
alias vi='vim'
alias sudo='sudo '
export EDITOR=vim
export P4PORT=p4server.example.com:1666
# Generated by Vagrant
EOF

echo "color elflord" >> /etc/vimrc

echo "[TASK 3] Creating Admin account [$SYSTEM_ADMIN] with sudo privileges"
useradd -s /bin/bash -c "System Admin" $SYSTEM_ADMIN
echo "$SYSTEM_ADMIN" | passwd --stdin $SYSTEM_ADMIN >/dev/null 2>&1
echo "$SYSTEM_ADMIN ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

echo "[TASK 4] Creating Perforce admin user account [$P4ADMIN_USER]"
useradd -s /bin/bash -c "Perforce Admin" $P4ADMIN_USER
echo "$P4ADMIN_USER" | passwd --stdin $P4ADMIN_USER >/dev/null 2>&1

echo "[TASK 5] Downloading Perforce binaries $P4BINARIES"
for prog in $P4BINARIES
do
  wget -nd -q -m --ftp-user=anonymous --ftp-password=x ftp://ftp.perforce.com/perforce/r18.1/bin.linux26x86_64/$prog -O /usr/local/bin/$prog
  chmod +x /usr/local/bin/$prog
done

echo "[TASK 6] Enabling password authentication in sshd config"
sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
systemctl reload sshd

echo "[TASK 7] Update /etc/hosts"
cat >>/etc/hosts <<EOF

#=== Added by Vagrant ===#
172.42.42.111 p4server.example.com p4server
172.42.42.112 p4client.example.com p4client
#=== Added by Vagrant ===#
EOF

echo "[TASK 8] Set git global configs for $P4ADMIN_USER user"
su - $P4ADMIN_USER -c "git config --global http.sslVerify false"
su - $P4ADMIN_USER -c "git config --global user.name \"$P4ADMIN_USER\""
su - $P4ADMIN_USER -c "git config --global user.email \"$P4ADMIN_USER@localhost\""
